import { Inter} from "next/font/google";
import "./globals.css";
import LeftSideBar from "./components/LeftSideBar";
import RightMenu from "./components/RightMenu";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
     
      className={`${inter.className} h-full antialiased`}
    >
      <body className=" text-white bg-black">
        
        {/* Container */}
        <div className="min-h-screen flex flex-col md:flex-row">

          {/* LEFT SIDEBAR */}
          <aside className="w-full md:w-[25%] md:fixed md:top-4 md:bottom-4 md:left-4 overflow-hidden">
            <LeftSideBar />
          </aside>

          {/* MAIN CONTENT */}
          <main className="w-full md:ml-[25%] md:mr-[15%] md:w-[60%] px-4 py-4">
            {children}
          </main>

          {/* RIGHT MENU */}
          <aside className="w-full md:w-[15%] md:fixed md:top-4 md:bottom-4 md:right-4  rounded-xl overflow-hidden">
            <RightMenu />
          </aside>

        </div>

      </body>
    </html>
  );
}